name: clj-kondo linting

on: [push]

jobs:
  self-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src test
        # secrets.GITHUB_TOKEN is needed here
        # to publish annotations back to github
        # this action is not storing or sending it anywhere
        github_token: ${{ secrets.GITHUB_TOKEN }}
